---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    purpose: pki-tls
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  type: default
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  timeout: 8m
  chart:
    spec:
      chart: cert-manager
      version: "v1.21.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    crds:
      enabled: true          # installe les CRDs avec le chart
    # bornes basses pour un lab
    resources:
      requests: {cpu: 10m, memory: 32Mi}
      limits: {cpu: 100m, memory: 128Mi}
    webhook:
      resources:
        requests: {cpu: 10m, memory: 32Mi}
        limits: {cpu: 100m, memory: 128Mi}
    cainjector:
      resources:
        requests: {cpu: 10m, memory: 32Mi}
        limits: {cpu: 100m, memory: 128Mi}
