apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram
    namespace: monitoring
type: Opaque
stringData:
    bot_token: ENC[AES256_GCM,data:5FN8Dz55tYcmNWGISYSnpqFfg+5a+F3yX0Bswotw9fC6Au3Ljzm63aImShl0pA==,iv:ImxRVxyRJxF2cTnwkRYwo9hJWi+NsQLv6CEGQG6h7m4=,tag:TJr+rCbZntYawun9W7c/Aw==,type:str]
    chat_id: ENC[AES256_GCM,data:AYxwkvzHOaa0sA==,iv:a/zVSu/0HhbKZDnLexVev3VyT9Ii2II/tVRygURiyQ4=,tag:YQ+lsit0qGMH8Soi7yVVmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZmFVNDkvcVcrUjMyM0dR
            KzU3SjdmcVB1MXljMHJUeGh5S3dndmtWaVR3CjdxTXpvaHRkWnh3WmN4REx4TUI4
            ZjVqMFp0YnhTZXVSUDRFRWtKMm1mSGMKLS0tIDh1UGlpOVVXL1F5YS94djhRdlht
            T2QxNnBxZTg5K3c4M25ZTkZ1ejZrSG8KG/W0RoMep49kPq3t7QvMcUwKTG8YOvIv
            5Btwso6G6feL5CwINNUDzzsf27U20oYPluI0YXn6TBFNV92jX7N19g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1czdh5vwj9kk5rcmcxj99gj7v20kq7ktj8nlnkjt7sr900r2yguas5kdwpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T01:42:37Z"
    mac: ENC[AES256_GCM,data:jgEet9X3bad0SwiiIjd0qSmJerG2JN+Nt+0CgsIIyF1s3dmxglDyVc9nQIsGmVKCF6nRw9oAhyUReEmrVrHFZ6xeTzkFfIYsqmhzI5srQS4k2bJW7L6JIf/jwyH8J+lGAxaxBb3AxUU4C8BGCb8amVdK44NUTFKuKRnHpulhhhE=,iv:h9DOEwqh94gYrBPEIef//OD/ULK3phSTO9IBe1lZQzk=,tag:hRtOd4YFMNDIM8KLNCMHYA==,type:str]
    version: 3.13.3
