apiVersion: v1
data:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:WsuRyGzNPNEt0y5vBalJD37rqoX5k2f0JkKnoj7q5DNqC8RWZDUn89rI39zBiEA4E84dfgCeUoLhE3e1ijEc+EZI8C9Su3I08+AgXNylX/8fY1+w6aCs7LECcLQ0kF2EX0MVcg==,iv:ASEs4B2TG/LxQdG+2Bso1Tbp2BT54OLr5CcAQp988Kk=,tag:SY29Q9bbTAfP/JRM9pBEBg==,type:str]
kind: Secret
metadata:
    annotations: {}
    name: t3mp3st-secrets
    namespace: t3mp3st
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dnQvSWVzRlEyOExqOGNs
            N1hZR0FmbmdVRVdtbjRHRk81Zi9BSjNEL1E0Ckc4ZkRkVFV5bXNLUnRFUkVKTFgz
            emhITzA5NlgySmFQcGFrOEFONGlXSG8KLS0tIHJ5S3lzdlNPVnJtNnhTT3ZzRklB
            NWE3Rm1xeVRjOWNvOS9aZTFLVVEydHcKYgnZlfznrwiIaJQZyaeu3wgKMXSM5SWC
            bQCBjmZDmB0VZH0goYNdBiZg0V8pfqfYA/HAdhCVFuvTebSZ6drkXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1czdh5vwj9kk5rcmcxj99gj7v20kq7ktj8nlnkjt7sr900r2yguas5kdwpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T00:55:40Z"
    mac: ENC[AES256_GCM,data:kRVFsXtjyHh26N/u1ba95bgOti6MGWAVh919r3PMIgqntlb3+M6JgO4G3LX1agqKkSEBOs5fnwK//Z34TXooiQdCSY+BxYYFkGVxWnRs/fvjsA6k2zJ9E8vik5+UWTkzFqyQsFfE8aBTDe5YDHneGuDXimaPpCOlp2HZhVUUPUk=,iv:BF7AYLsg9BXUuJJaVKAOtJhzeXJAfnUv1hoSmY3DA1Y=,tag:HF5kw7UEm47lQ8NN8mm2KA==,type:str]
    version: 3.13.3
