apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hermes-web
  namespace: hermes
spec:
  ingressClassName: traefik
  rules:
    - host: hermes.cloud4dev.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hermes
                port:
                  number: 9119