apiVersion: v1
data:
    A2A_BEARER_TOKEN: ENC[AES256_GCM,data:CHX2Dj676Vq9kSVrlde9qg79LI6rVKTFpkQcvp7tA5J1jj1H45SxgmVlUO7+FUWV2iWdL2+7lOZVSml0PKO8g4DWvnusSVAO,iv:PmqJwyoXs2KA6Zgg2rMAs94geiISww2AmDnSMhEmNIA=,tag:TR3VSemGbtD4aJMK9DGuxw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:ChPUZ5o71IlTrU81UMUjKWlvlES/5m4px9PeMmdBn6EeIqIoRLQjmh5Qy9xkrLfNkl1ZQUssIezdyhq8/4lvijA8P0b2MRZ2VXn0Mr7FKqHXmxQ3rw7Jy5oz/oRXJCuZsKlCow==,iv:gaE7z1mN4I2JCd5b8hY2yVvbmOlU/itH7/j0Oz9fofg=,tag:7pPp24qWPa8yd3+xsRxm5A==,type:str]
kind: Secret
metadata:
    annotations: {}
    name: hermes-secrets
    namespace: hermes
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWWNQQjZORG5tWTJ6bE5t
            NzU5a0w3TlEyUmhoUm13YXZhaGtpQXNWOG5VCkpsSkJUeThDSjFHTnBIUk9WMmRB
            aWRmd29wdStHaXlYYUZoQ0xwbW15Y0EKLS0tIE5zTFltM3VVM2NnWmM1VFVmVmYv
            TzFMZW9xZVR0WDYvOXBJS1JyUEtxL2cKUJgzwCkIbkKSlJqxtePPL3XnQMBBYtCq
            HQduIgiiel5XEj6guxQbBBwFX1SGglj6DpSYr7D8se7x3BGBsGmLwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1czdh5vwj9kk5rcmcxj99gj7v20kq7ktj8nlnkjt7sr900r2yguas5kdwpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T00:55:40Z"
    mac: ENC[AES256_GCM,data:AdAW3R46W80rS+G7Ers027nGAbH/fZwgLSISfagR1DL8jbq7Fm78yLEOeR7flki3NfbtZ6DawL8sIZMDRbKyFXrtTzs4R8Ok7hldxwXzjwHC9gy+U49OSs46SdHeIlZM/ikSB8ZrDHYUPJdX35c8p4sW8ZhtxrOrKWYX099EQpY=,iv:rcEHk0JOeQmdHj+aY9xpzM3El+Q1fEKm1Fo7BlN6TNs=,tag:Yk8ZwfCFrk8iKHJH9TiMFw==,type:str]
    version: 3.13.3
